import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import { chromium } from "playwright";
import { renderSite } from "../src/index.js";
import { catalogConfig, serviceConfig, stageCatalogAssets, writePng } from "./fixtures.js";

const executablePath = "/home/vitor/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome";

test("rendered Homes are contained, accessible, and complete at 390, 768, and 1440", async () => {
  const catalogRoot = mkdtempSync(join(tmpdir(), "seed-renderer-browser-catalog-")); const serviceRoot = mkdtempSync(join(tmpdir(), "seed-renderer-browser-service-")); let browser;
  try {
    stageCatalogAssets(catalogRoot); writePng(join(catalogRoot, "assets", "logo.png"), 600, 60); const catalog = catalogConfig(); catalog.assets!.push({ id: "logo", path: "assets/logo.png", role: "logo", alt: "Marca", width: 600, height: 60, provenance: { kind: "caller-staged", source: "fixture", license: "teste" } }); catalog.company.logoAssetId = "logo";
    const hero = catalog.pages[0]!.sections.find((item) => item.kind === "hero"); if (hero?.kind === "hero") hero.actions.push({ label: "Ver opções", href: "/opcoes" }); const cta = catalog.pages[0]!.sections.find((item) => item.kind === "cta"); if (cta?.kind === "cta") cta.actions.push({ label: "Saiba mais", href: "/saiba-mais" }); renderSite(catalog, { outDir: catalogRoot }); renderSite(serviceConfig(), { outDir: serviceRoot });
    browser = await chromium.launch({ executablePath, headless: true });
    for (const width of [390, 768, 1440]) for (const [variant, root] of [["catalog", catalogRoot], ["service", serviceRoot]] as const) {
      const context = await browser.newContext({ viewport: { width, height: 900 }, reducedMotion: "reduce" }); const page = await context.newPage(); const diagnostics: string[] = []; const network: string[] = [];
      page.on("console", (message) => { if (message.type() === "error") diagnostics.push(message.text()); }); page.on("pageerror", (error) => diagnostics.push(error.message)); await page.addInitScript("globalThis.__name = (fn) => fn"); await page.route(/^https?:\/\//, async (route) => { network.push(route.request().url()); await route.abort("blockedbyclient"); }); await page.goto(pathToFileURL(join(root, "index.html")).href, { waitUntil: "load" });
      const observed = await page.evaluate(() => {
        const rgb = (value: string): number[] => (value.match(/[\d.]+/g) ?? []).slice(0, 3).map(Number); const luminance = (color: number[]): number => color.map((v) => v / 255).map((v) => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4).reduce((sum, v, i) => sum + v * [.2126, .7152, .0722][i]!, 0); const contrast = (a: number[], b: number[]): number => { const [light, dark] = [luminance(a), luminance(b)].sort((x, y) => y - x); return (light! + .05) / (dark! + .05); }; const background = (node: Element): string => { let current: Element | null = node; while (current) { const color = getComputedStyle(current).backgroundColor; if (color && !color.endsWith(", 0)") && color !== "transparent") return color; current = current.parentElement; } return "rgb(255, 255, 255)"; };
        const actionContrast = [...document.querySelectorAll(".hero .button,.cta .button")].map((node) => contrast(rgb(getComputedStyle(node).color), rgb(background(node)))); const logo = document.querySelector(".brand-logo img")?.getBoundingClientRect(); const header = document.querySelector(".site-header")?.getBoundingClientRect(); const heroGrid = document.querySelector(".hero-grid.no-media"); const copy = heroGrid?.querySelector(".hero-copy")?.getBoundingClientRect(); const grid = heroGrid?.getBoundingClientRect();
        return { overflow: document.documentElement.scrollWidth > innerWidth, overflowWidth: document.documentElement.scrollWidth, wide: [...document.querySelectorAll("*")].filter((node) => node.getBoundingClientRect().right > innerWidth + 1 || node.scrollWidth > node.clientWidth + 1).slice(0, 6).map((node) => `${node.tagName}.${node.className}:${node.getBoundingClientRect().right}/${node.scrollWidth}/${node.clientWidth}`), main: !!document.querySelector("main"), sections: document.querySelectorAll("[data-home-section]").length, reduced: getComputedStyle(document.documentElement).scrollBehavior, images: [...document.images].map((image) => ({ complete: image.complete, width: image.naturalWidth, height: image.naturalHeight })), targets: [...document.querySelectorAll("a,summary")].filter((node) => { const style = getComputedStyle(node); return node.getClientRects().length > 0 && style.display !== "none" && style.visibility !== "hidden"; }).map((node) => node.getBoundingClientRect().height), actionContrast, logoContained: !logo || !!header && logo.width <= 220 && logo.height <= 52 && logo.top >= header.top && logo.bottom <= header.bottom, noMediaFull: !heroGrid || innerWidth < 720 || (getComputedStyle(heroGrid).display === "block" && !!copy && !!grid && copy.width / grid.width > .75) };
      });
      assert.equal(observed.overflow, false, `${variant} overflow at ${width}: ${observed.overflowWidth} ${observed.wide.join("|")}`); assert.equal(observed.main, true); assert.ok(observed.sections >= 9); assert.equal(observed.reduced, "auto"); if (variant === "catalog") assert.ok(observed.images.length > 0); assert.ok(observed.images.every((image) => image.complete && image.width > 0 && image.height > 0)); assert.ok(observed.targets.every((height) => height >= 44), `short target at ${width}: ${observed.targets.join(",")}`); assert.ok(observed.actionContrast.every((ratio) => ratio >= 4.5), `low action contrast: ${observed.actionContrast.join(",")}`); assert.equal(observed.logoContained, true, `${variant} logo escaped header at ${width}`); assert.equal(observed.noMediaFull, true, `${variant} no-media hero is not full-width at ${width}`); assert.deepEqual(diagnostics, []); assert.deepEqual(network, []); await context.close();
    }
  } finally { if (browser) await browser.close(); rmSync(catalogRoot, { recursive: true, force: true }); rmSync(serviceRoot, { recursive: true, force: true }); }
});
